config/routes.rb
Sorcery::Application.routes.draw do
  get "logout" => "sessions#destroy", :as => "logout"  
  get "login" => "sessions#new", :as => "login"  
  get "signup" => "users#new", :as => "signup"  
  resources :users 
  resources :sessions  
  get "secret" => "home#secret", :as => "secret"  
  root :to => "home#index"  

  

end

app/models/user.rb
class User < ActiveRecord::Base
  authenticates_with_sorcery!
  validates :email, presence: true , uniqueness: {case_sensitive: false}
  validates :password, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  private
    def not_authenticated
      redirect_to login_url, :alert => "First log in to view this page."
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_filter :require_login, :only => :secret
  def index
  end

  def secret
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = login(params[:email], params[:password], params[:remember_me])
    if user
      redirect_back_or_to root_url, :notice =>"Successfully log in!"
    else
      falsh.now.alert = "Email or Password was invalid"
    end
  end

  def destroy
    logout
    redirect_to root_url, :notice=>"Logged out!"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to root_url, :notice => "Successfully Sign up!"
    else
      render :new
    end
  end

  private
    def user_params
      params.require(:user).permit(:email, :password)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/index.html.erb
<h1>Welcome!</h1>
<p>This is a sample_app for sorcery.</p>

app/views/home/secret.html.erb
<h1>Secret page for login user.</h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Sorcery</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div id="container">
    <div id="nav">
      <% if current_user %>
        Logged in as <%= current_user.email %>.
        <%= link_to "Log out", logout_path %>
      <% else %>
        <%= link_to "Sign up", signup_path %> or
        <%= link_to "Log in", login_path %>.
      <% end %>
    </div>
    <% flash.each do |name,msg| %>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    <% end %>
    <%= yield %>
  </div>
</body>
</html>

app/views/users/new.html.erb
<h1>Sign up</h1>
<%= form_for @user do |f| %>
  <% if @user.errors.any?%>
    <div class="error_messages">
      <h2>Form is invalid</h2>
      <ul>  
        <% for message in @user.errors.full_messages %>  
	  <li><%= message %></li>  
        <% end %> 
      </ul>  
    </div>  
  <% end %> 
  <div class="field">
    <%= f.label :email %>
    <%= f.text_field :email %>
  <div class="field">
    <%= f.label :password %>
    <%= f.text_field :password %>
  </div>
  <div class="action"><%= f.submit %></div>
<% end %>